### ISSUE TITLE
Problème de mise à jour du champs image, pour opengraph

### ISSUE THREAD

**Issue by Jean-Baptiste-Lasselle** [3forges/juste-un-curieux#29]
J'ai changé la description, le titre, et l'image, tous les champs sont mis à jour automatiquement, cependant l'image reste l'ancienne. 

Voici une chose que j'ai trouvée sur cette question :  

![image](https://github.com/3forges/juste-un-curieux/assets/35227860/761686b6-4112-4c30-b877-34ecb53e0482)

**Comment by Jean-Baptiste-Lasselle** [comment]
* https://discourse.webflow.com/t/i-change-the-open-graph-image-and-now-its-not-displaying-the-new-image/198717
* https://discourse.webflow.com/t/open-graph-image-not-updating-on-new-home-page/202205/4

**Comment by Jean-Baptiste-Lasselle** [comment]
https://stackoverflow.com/questions/7572441/facebook-like-showing-cached-version-ogimage-way-to-refresh-or-reindex-it

**Comment by Jean-Baptiste-Lasselle** [comment]
https://developers.facebook.com/tools/debug/

**Comment by Jean-Baptiste-Lasselle** [comment]
https://www.opengraph.xyz/

**Comment by Jean-Baptiste-Lasselle** [comment]
Ok, lorsque l'o partage le lien du site de Justin curieux sur un réseau social `LAMBDA`, il y a 2 points sur lesquels un cache peut intervenir : 
* Dans l'infra ds laquelle le déploiement du site est fait, ici Vercel
* Au niveau de l'infra du réseau social `LAMBDA`
* J'ai testé le rendu opengraph d'un share sur Facebook, et j'ai effectivment tjrs l'ancienne image: ce ne peut donc être qu'au niveau de Vercel, qu'il y a un cache
* J'ai recherché et ai trouvé ces références, qui confirment que mes dpéloiement verel ont donné lieu à un cache automatique : 
  * https://vercel.com/docs/edge-network/caching
  * https://vercel.com/docs/edge-network/caching#static-files-caching
  
  
  
![image](https://github.com/3forges/juste-un-curieux/assets/35227860/8f6e88f4-c297-419a-ae84-733967c10db0)

Apparrement, donc, au maximum au bout de 31 jours le changement devrait intervenir

**Comment by BorisTherin** [comment]
ok ok, j'ai pas tous lus mais je vois l'embrouille. 
Ceci dit, ces deploiement vercel ou autre vont cachés par rapport au nom de domaine ? les deploiements 'dev' tel que vercel & surge polluent ils le deploiement final (sur la nom de domaine de justin curieux par exemple) ?

**Comment by Jean-Baptiste-Lasselle** [comment]
Le problème est désormais résolu, la question est simplement que l'image référencée par son URL, doit exister... cf. `index.astro`
