### ISSUE TITLE
Twitch player

### ISSUE THREAD

**Issue by Jean-Baptiste-Lasselle** [3forges/juste-un-curieux#3]
On veut un Player Twitch sur le premier écran en haut de page, 
Il n'est pas évident de rendre complètement responsive le player,

**Comment by BorisTherin** [comment]
j'ai documenté mon TwitchPlayer. ~~je pense qu'il pourrait partir en Review~~

# Make your Embeded Twitch Player pretty responsive 🔧
_Twitch player isnt that bad, it's full reponsive when finishing the job as a frontend dev_
* this article detail the way i handled with a Twitch player on a web site, & bringed it to the more responsivity i could

## Goals
* we want our TwitchPlayer reponsive :
	* at load
	* at resize (web) rotate (mobile)
	* we want to have the chat layout every time it's possible
	* we dont want the video layer being cut
------------------------------------------------------

* What we got from Twitch API Embedding Everything (https://dev.twitch.tv/docs/embed/everything/)
```js
<!-- Add a placeholder for the Twitch embed -->
<div id="twitch-embed"></div>

<!-- Load the Twitch embed JavaScript file -->
<script src="https://embed.twitch.tv/embed/v1.js"></script>

<!-- Create a Twitch.Embed object that will render within the "twitch-embed" element -->
<script type="text/javascript">
	new Twitch.Embed("twitch-embed", {
	width: 854,
	height: 480,
	channel: "monstercat",
	// Only needed if this page is going to be embedded on other websites
	parent: ["embed.example.com", "othersite.example.com"]
	})
</script>
```

This player is full responsive, depending its width, it will fold/unfold to keep at best in every screen resolution.

* With the layout option : `layout: 'video-and-chat'` the player will provide the chat, right or down the video depending the width, to fit into the best view.

But at the moment, the player wont be responsive with resize (web) or rotate (mobile), we need to attach listeners to events in order to detect resizing or rotation.

* Nothing really hard here

```js
const inject = document.createElement('script')
inject.type = "text/javascript"
inject.src = "https://embed.twitch.tv/embed/v1.js"
inject.onload = () => {
	new Twitch.Embed("twitch-embed", {
		width: 854,
		height: 480,
		channel: "monstercat",
		layout: "video-and-chat",
		// Only needed if this page is going to be embedded on other websites
		parent: ["embed.example.com", "othersite.example.com"]
	})
	window.addEventListener('resize', () => {
		...
	})
}
document.getElementById("twitch-embed").append(inject)
```

* The hard one is about what will u resize, as the player is injected with a remote script.
* Inspecting our DOM, we can observe the final injections, script & iframe tag in our `<div id="twitch-embed"></div>`

```js
<div id="twitch-embed">
  <script src="https://embed.twitch.tv/embed/v1.js"></script>
  <iframe 
    src="https://embed.twitch.tv?autoplay=false&amp;channel=radiojaune&amp;height=400&amp;layout=video-and-chat&amp;parent=embed.example.com&amp;parent=radiojaune.com&amp;parent=localhost&amp;referrer=http%3A%2F%2Flocalhost%3A3000%2F&amp;width=800" 
    allowfullscreen="" 
    scrolling="no" 
    frameborder="0" 
    allow="autoplay; fullscreen" 
    title="Twitch" 
    sandbox="allow-modals allow-scripts allow-same-origin allow-popups allow-popups-to-escape-sandbox" 
    width="472.6666666666667" 
    height="485.5"></iframe>
</div>
```

* what we want is : 
	* get sure to hit the TwitchPlayer's ```<iframe>```
	* attach our EventListeners
		* Twitch.Embed.VIDEO_READY
		* Twitch.Embed.VIDEO_PLAY
		* 'resize'

```js
const embedDiv = document.getElementById("twitch-embed")
for (var i=0; i < embedDiv.getElementsByTagName("iframe").length; i++) {
	if (embedDiv.getElementsByTagName("iframe")[i].title == "Twitch") {
		const frameId = i
		window.addEventListener("resize", () => { ... })
	}
}
```
# Benefits: keep connected to Twitch-Api
----------------------------------------

* In my experience, such players are wanted on a basic (or not) landing page.
* Watchin' for VIDEO_READY & VIDEO_PLAY is our key for any client-side design (opacity: 0.3 to 1 in this example, as i build my landing-page, with the player to be on top of a canvas animated background)
* Keep creative

```js
embed.addEventListener(Twitch.Embed.VIDEO_READY, () => {
		var player = embed.getPlayer()
		player.play()
		console.log("TwitchPlayer: VIDEO_READY")
	})
	embed.addEventListener(Twitch.Embed.VIDEO_PLAY, () => {
		document.getElementById("twitch-embed").style.opacity = 1
		console.log("TwitchPlayer: VIDEO_PLAY")
	})
```

# The bad thing about TwitchPlayer & `layout: 'video-and-chat'`
--------------------------------------------------------------

* So, we are able to have pretty responsive resized (web) or rotated (mobile) Player, but as we're providing `layout: 'video-and-chat'` we can observe the video layer being cut under a 800px screen size ... (i wont comment)

* Unfortunatly, `layout` isnt an iframe property, but a script argument :
&lt;iframe src="...tv?autoplay=false&amp;channel=monstercat&amp;height=400&amp;`layout=video-and-chat`&amp;parent=..."

* we need to update, the best way we can our iframe src property _( & make sure to update once, not zounds )_, where `layout` options stand. 

* we will keep the original script arguments & only switch `layout=`_value_

```js
const iframe = embedDiv.getElementsByTagName("iframe")[frameId]
if (
	window.innerWidth < 800 && 
	iframe.src.replace("layout=video-and-chat","layout=video") != iframe.src 
	) {	// UPDATE ONCE (maybe 2)
		iframe.src = iframe.src.replace("layout=video-and-chat","layout=video")
		console.log("switching player src")
} else if (
	window.innerWidth > 800 && 
	iframe.src.replace("layout=video-and-chat","") == iframe.src 
	) { // UPDATE ONCE 
		iframe.src = iframe.src.replace("layout=video","layout=video-and-chat")
		console.log("switching player src")
}
```

# Final script ✅
-----------------

* Your TwitchPlayer with everythings full responsive:

```js
<div id="twitch-embed" class="absolute" style="opacity: 0.3; z-index:5;"></div>
<script type="text/javascript">
/**
 *  CONFIG YOUR FLAVOR
 */
const chatLayout = true                   // layout option [true: 'video-and-chat' | false: 'video']
const pixelRangeToSwitchSrcOptions = 800 // minimal pixel range to fire src option replacement when chatLayout=true (TwitchPlayer constraint (800 pixels), but may change), (window.innerWidth+1 to disable)
const widthRatio = 1.5                 // TwitchPlayer width screen ratio
const heightRatio = 2                 // TwitchPlayer height screen ratio
const channel = 'monstercat'         // your channel
const webUrls = ["embed.example.com", "othersite.example.com"]   // your network
const autoplay = true              // Twitch.Embed.VIDEO_READY action
const verbose = true              // console feedback on|off

// TWITCH API SCRIPT INJECTION
const inject = document.createElement("script")
inject.type = "text/javascript"
inject.src = "https://embed.twitch.tv/embed/v1.js"
inject.onload = () => { startTwitch() }
document.getElementById("twitch-embed").append(inject)
// TWITCHPLAYER INITIALISATION & DEDICATED LISTENERS
function startTwitch() {
	embed = new Twitch.Embed("twitch-embed", {
		width: (window.innerWidth/widthRatio),
		height: (window.innerHeight/heightRatio),
		channel: channel,
		layout: "video"+((window.innerWidth > pixelRangeToSwitchSrcOptions && chatLayout)?"-and-chat":""),
		parent: webUrls
	})
	// TWITCH API
	embed.addEventListener(Twitch.Embed.VIDEO_READY, () => {
		var player = embed.getPlayer()
		if (autoplay) player.play()
		if (verbose) console.log("TwitchPlayer: VIDEO_READY")
	})
	embed.addEventListener(Twitch.Embed.VIDEO_PLAY, () => {
		// KEEP CREATIVE/INTERACTIVE HERE
		document.getElementById("twitch-embed").style.opacity = 1
		if (verbose) console.log("TwitchPlayer: VIDEO_PLAY")
	})
	// MORE RESPONSIVTY (WEB)
	const embedDiv = document.getElementById("twitch-embed")    
	for (var i=0; i < embedDiv.getElementsByTagName("iframe").length; i++) {
		// FIND THE RIGHT NODE
		if (embedDiv.getElementsByTagName("iframe")[i].title == "Twitch") {
			if (verbose) console.log("attaching resize Events on TwitchPlayer-frame["+i+"]")
			const frameId = i
			window.addEventListener("resize", () => {
				// IFRAME SIZES
				embedDiv.getElementsByTagName("iframe")[frameId].width = window.innerWidth/widthRatio
				embedDiv.getElementsByTagName("iframe")[frameId].height = window.innerHeight/heightRatio
				const iframe = embedDiv.getElementsByTagName("iframe")[frameId]
				// IFRAME SRC OPTIONS SWITCH 
				if (
					window.innerWidth < pixelRangeToSwitchSrcOptions && 
					iframe.src.replace("layout=video-and-chat","") != iframe.src 
					) {	// UPDATE ONCE
							iframe.src = iframe.src.replace("layout=video-and-chat","layout=video")
							if (verbose) console.log("switching player src")
					} else if (
						window.innerWidth >= pixelRangeToSwitchSrcOptions && 
						iframe.src.replace("layout=video-and-chat","") == iframe.src 
					) { // UPDATE ONCE
							iframe.src = iframe.src.replace("layout=video","layout=video-and-chat")
							if (verbose) console.log("switching player src")
					}
			})
		}
	}
}
</script>
```

[ResponsiveTwitchPlayer.md](https://github.com/3forges/juste-un-curieux/files/12405098/ResponsiveTwitchPlayer.md)

# &#127873; Feel free to git my preact component for 🚀Astro Island 
-------------------------------------------------------------------
* <sub><sup>`<TwitchPlayer client:only="preact" />`</sup></sub>
	* https://github.com/BorisTherin/ortf-land-astro-template/blob/main/src/components/TwitchPlayer.tsx

**Comment by BorisTherin** [comment]
aussi :

```js
<div id="twitch-embed" class="absolute grid justify-items-center items-center min-w-[80%] min-h-[50%]" style="opacity: 0.3; z-index:5;"></div>
``` 

contient le player de facon responsive si je change mon script:

```js
// FIND THE RIGHT NODE
if (embedDiv.getElementsByTagName("iframe")[i].title == "Twitch") {
  if (verbose) console.log("attaching resize Events on TwitchPlayer-frame["+i+"]")
    const frameId = i
``` 

en 

```js
// FIND THE RIGHT NODE
if (embedDiv.getElementsByTagName("iframe")[i].title == "Twitch") {
  if (verbose) console.log("attaching resize Events on TwitchPlayer-frame["+i+"]")
    const frameId = i
    embedDiv.getElementsByTagName("iframe")[frameId].width = "100%"
    embedDiv.getElementsByTagName("iframe")[frameId].height = "100%"
``` 
je peux alors me passer des eventsListeners 'resisze' (concernant le resize, car il restera pertinent de changer le layout pour les petites resolutuon)

Le player Twitch reagit tout aussi bien & naturellement

**Comment by BorisTherin** [comment]
aussi, en changeant le `<div id='twitch-embed'>`  si l'on force la taille du container qui accueil le twitchplayer, & que l'on intervient sur le width/height de l'iframe injectée pour les passer a "100%" :

```js
<div id="twitch-embed" class="absolute grid justify-items-center items-center min-w-[80%] min-h-[50%]" style="opacity: 0.3; z-index:5;"></div>
``` 

contient le player de facon responsive, alors je change mon script:

```js
// FIND THE RIGHT NODE
if (embedDiv.getElementsByTagName("iframe")[i].title == "Twitch") {
  if (verbose) console.log("attaching resize Events on TwitchPlayer-frame["+i+"]")
  const frameId = i
  window.addEventListener("resize", () => {
      ...
``` 

en 

```js
// FIND THE RIGHT NODE
if (embedDiv.getElementsByTagName("iframe")[i].title == "Twitch") {
  if (verbose) console.log("attaching resize Events on TwitchPlayer-frame["+i+"]")
  const frameId = i
  embedDiv.getElementsByTagName("iframe")[frameId].width = "100%"
  embedDiv.getElementsByTagName("iframe")[frameId].height = "100%"
  window.addEventListener("resize", () => {
      ...
``` 
& on peux desormais se passer des eventsListeners 'resize' (concernant le resize, car il restera pertinent de changer le layout pour les petites resolutions, a moins de trouver une autre solution)

Le player Twitch reagit tout aussi bien & naturellement

**Comment by BorisTherin** [comment]
~~fait interressant, dans cette configuration, le reponsive naturel du player masque le layer video en dessous de 670px de largeur, alors que precedement, c'etait en dessous de 800px~~

c'est bien mieux que ça, le chargement naturel pour les petites resolutions affiche le layer video plutot que le chat seulement, l'affichage de chaques mobile dans la console est pile poil

pushed sur features/calendar

**Comment by BorisTherin** [comment]
pourtant , coté console :
![image](https://github.com/3forges/juste-un-curieux/assets/89749441/011f22d4-a314-4039-8c5f-2b978a770f1f)
![image](https://github.com/3forges/juste-un-curieux/assets/89749441/23bd77ce-1566-4393-b519-bc7777474fd1)


* width & height = "100%"

& coté DOM:
![image](https://github.com/3forges/juste-un-curieux/assets/89749441/0148207f-ede7-469e-b79b-50685912c263)

* width & height = valeures numériques

**Comment by BorisTherin** [comment]
# script final TwitchPlayer.astro

```js
---
---
<div 
    id="twitch-embed" 
    class="absolute grid justify-items-center items-center min-w-[80%] min-h-[50%] opacity-30 z-5" 
></div>
<script type="text/javascript" src="https://embed.twitch.tv/embed/v1.js" ></script>
<script>
const chatLayout = true                  // layout option [video|video-and-chat]
const pixelRangeToSwitchSrcOptions = 799 // minimal pixel range to fire src option replacement when chatLayout=true (TwitchPlayer constraint (800), but may change), (windowDimensions.width+1 to disable)
const widthRatio = 1.5                 // TwitchPlayer width screen ratio
const heightRatio = 2                 // TwitchPlayer height screen ratio
const channel = 'radiojaune'         // your channel
const webUrls = ["embed.example.com", "othersite.example.com"]   // your network
const autoplay = true              // Twitch.Embed.VIDEO_READY action
const verbose = true              // console feedback on|off

embed = new Twitch.Embed("twitch-embed", {
    width: "100%",
    height: "100%",
    channel: channel,
    layout: "video"+((window.innerWidth>pixelRangeToSwitchSrcOptions && chatLayout)?"-and-chat":""),
    parent: webUrls
});
embed.addEventListener(Twitch.Embed.VIDEO_READY, () => {
    var player = embed.getPlayer()
    if (autoplay) player.play()
    if (verbose) console.log("TwitchPlayer: VIDEO_READY")
});
embed.addEventListener(Twitch.Embed.VIDEO_PLAY, () => {
    document.getElementById("twitch-embed").style.opacity = 1;
    document.getElementById("calendarContainer").style.display = "none";
    if (verbose) console.log("TwitchPlayer: VIDEO_PLAY")
});        
</script>
```

* width: **"100%"**,
* height: **"100%"**,

**Comment by BorisTherin** [comment]
petit soucis avec le domaine ancestor depuis https://justincurieux_feature_boris_twitch.surge.sh/

![image](https://github.com/3forges/juste-un-curieux/assets/89749441/3ad6f665-dd02-4789-a1b9-70c2368d244a)

**Comment by Jean-Baptiste-Lasselle** [comment]
note: 
* We found out that if deployed to surge.sh, the embeded twitch player has a major issue : apparently due to frame-ancestors policy , causing the player to not even appear at all, Twitch refuses to frame the channel to our website
* Yet deploying the exact same Twitch player to github pages and to vercel.app did work without experimenting the same issue at all

**Comment by BorisTherin** [comment]
test de ce matin :
j'ai push la meme page html basic twitchplayer, mais en prenant soin de raccourcir au mieux le cname.

https://spik-.surge.sh/

![image](https://github.com/3forges/juste-un-curieux/assets/89749441/a2fc50e1-0cf0-4457-8527-09dd45ba869c)


ca marche, voir quel serait la limite de taille du cname/domain, & le score SEO qui prend encore

**Comment by BorisTherin** [comment]
concernant l'opacité, nous n'utiliserons plus l'event TWITCH.PLAY, mais une transition de quelques secondes qui ramenera le player twitch opaque

**Comment by BorisTherin** [comment]
Nous avons actuellement 4 composants TwitchPlayer:
* un composant .astro (non hydraté)
* un composant .tsx (preact#1) qui injecte le script remote twitch  (nous donnant la class TWITCH), qui attend son chargement et initialise le player. (full JS)
```js
import { h } from 'preact'

export function TwitchPlayer() {

    /**
     *  CONFIG YOUR FLAVOR
     */
    const chatLayout = true               // layout option [video|video-and-chat]
    const channel = 'monstercat'          // your channel
    //const webUrls = '"surge.sh"'      // your network
    const autoplay = true              // Twitch.Embed.VIDEO_READY action
    const verbose = true              // console feedback on|off

    const embedTwitchScript = '"use strict";'+      // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode
    'const inject = document.createElement("script");'+
    'inject.type = "text/javascript";'+
    'inject.src = "https://embed.twitch.tv/embed/v1.js";'+
    'inject.onload = () => { startTwitch() };'+
    'document.getElementById("twitch-embed").append(inject);'+
    'function startTwitch() {' + 
        'let embed = new Twitch.Embed("twitch-embed", {'+
            'width: "100%",'+
            'height: "100%",'+
            'theme: "light",'+
            'autoplay: '+autoplay+','+
            'channel: "'+channel+'",'+
            'muted: true,'+
            'layout: "video'+((chatLayout)?"-and-chat":"")+'",'+
            'parent: []'+
        '});'+
    '};'

    return (
        <>
            <div id="twitch-embed" class="absolute grid justify-items-center items-center min-w-[80%] min-h-[50%] z-2 transition-opacity ease-linear duration-1000 from-100 to-30 "></div>
            {
                h(
                    'script',
                    { type: 'text/javascript'},
                    embedTwitchScript
                )
            }
        </>
    )
}
```
* un composant .tsx (preact#2) qui charge le script remote-twitch conventionnelement via une balise script & son src, puis compil une balise script contenant le code d'intanciation de la Class TWITCH
```js
import { h } from 'preact'

export function TwitchPlayer2() {
    
    const embedTwitchScript = 'var embed = new Twitch.Embed(\'twitch-embed\', {'+
        'width: \'100%\','+
        'height: \'100%\','+
        'allowfullscreen: true,'+
        'autoplay: true,'+
        'channel: \'radiojaune\','+
        'layout: \'video-and-chat\','+
        'parent: [\'radiojaune.com\']'+
    '});'
    
    return (
        <>
            <div 
                id="twitch-embed" 
                class="absolute grid justify-items-center items-center min-w-[80%] min-h-[50%] opacity-30 z-3" 
            ></div>
            <script type="text/javascript" src="https://embed.twitch.tv/embed/v1.js" ></script>
            { 
                h(
                    'script',
                    { type: 'text/javascript'},
                    embedTwitchScript
                )
            }
        </>
    )
}
```
* un composant .tsx (preact#3)  qui charge le script remote-twitch conventionnelement via une balise script & son src & appelle le code d'instanciation de la meme facon avec un .js local (/twitch.js)
```js
export function TwitchPlayer3() {    
    
    return (
        <>
            <div 
                id="twitch-embed" 
                class="absolute grid justify-items-center items-center min-w-[80%] min-h-[50%] z-2" 
            ></div>
            <script 
                type="text/javascript" 
                src="https://embed.twitch.tv/embed/v1.js"
            ></script>
            <script 
                type="text/javascript"
                src="/twitch.js"
            ></script>
        </>
    )
}
```

Chacuns de ces composant a été nettoyer de ses EventListeners

nos composant preact #2 & #3 plantent des lors qu'ils recoivent la client directive only="preact"
![image](https://github.com/3forges/juste-un-curieux/assets/89749441/b60c6442-f3e2-4df4-8f2f-a5d7b67d2321)

Restent muets (pas de player, pas d'erreures) avec les autres directives
![image](https://github.com/3forges/juste-un-curieux/assets/89749441/e28a19f5-6068-4f0c-8b1e-d477443bdbc2)


& enfin fonctionnent normalement des lors qu'on leur supprime leur client directive, et ne sont inclus dans une island astro
![image](https://github.com/3forges/juste-un-curieux/assets/89749441/3586ce9b-e647-4c03-8ef9-319cb19fe189)


le seul composant hydraté fonctionnel pour l'instant est le composant #1 avec sa client directive only="preact"

**Comment by Jean-Baptiste-Lasselle** [comment]
## Le Twitch Player est un problème pour la performance et les métrique lighthouse

Nous allons donc faire une novuelle passe de travail pour trouver d'autres mode de conception.
À terme, mais pas pour la première livraison Justn Curieux,nous essaierons par exemple un build wasm, pour embarquer toutes les dépendances avec le composant lui-même

#### Les composants React des autres

Une autre catégorie de pistes, consiste à regarder tous les composants react que l'on trouve pour faire un twitch player. 

En voici un premier que j'ai testé dans un projet Astro preact , basé sur le template astro landing page que l'on connaît bien :

* step 1, il faut ajouter correctement les dépandances preact/compat : 

```bash
pnpm add -D react@npm:@preact/compat react-dom@npm:@preact/compat
```

* step 2, ajouter la dépendance du composant react que l'on souhaite utiliser ds notre projet astro : 

```bash
# https://www.npmjs.com/package/react-twitch-embed
# https://github.com/moonstar-x/react-twitch-embed
pnpm add --save react-twitch-embed
```
* Step 3, Ajouter un `XTwitchPlayer.tsx` avec le code suivant : 

```Tsx
import React from 'preact/compat';
import { TwitchClip } from 'react-twitch-embed'; // <TwitchClip clip="AdventurousBusyWormTwitchRaid-7vDEE8L5ur9j9dzi" autoplay muted />

const XTwitchPlayer = () => {
  return (
    <TwitchClip clip="AdventurousBusyWormTwitchRaid-7vDEE8L5ur9j9dzi" autoplay muted />
  );
};

export default XTwitchPlayer;
```
* step 4, dans un `*.astro`, je vais utiliser `<TwitchClip clip="AdventurousBusyWormTwitchRaid-7vDEE8L5ur9j9dzi" autoplay muted />`

ce composant a déjà une qualité : il est vraiment responsive, j'ai testé. Sa performance, nous verrons.


#### Quelques références de discussions sur le sujet "Le Twitch embed démoli la perf de mon site web"

* https://discuss.dev.twitch.tv/t/how-to-mitigate-huge-performance-impact-of-a-twitch-embed/28182/2   là il parle d'un évènement "`DOMContentLoaded`"

**Comment by Jean-Baptiste-Lasselle** [comment]
> ## Le Twitch Player est un problème pour la performance et les métrique lighthouse
> Nous allons donc faire une novuelle passe de travail pour trouver d'autres mode de conception. À terme, mais pas pour la première livraison Justn Curieux,nous essaierons par exemple un build wasm, pour embarquer toutes les dépendances avec le composant lui-même
> 
> #### Les composants React des autres
> Une autre catégorie de pistes, consiste à regarder tous les composants react que l'on trouve pour faire un twitch player.
> 
> En voici un premier que j'ai testé dans un projet Astro preact , basé sur le template astro landing page que l'on connaît bien :
> 
> * step 1, il faut ajouter correctement les dépandances preact/compat :
> 
> ```shell
> pnpm add -D react@npm:@preact/compat react-dom@npm:@preact/compat
> ```
> 
> * step 2, ajouter la dépendance du composant react que l'on souhaite utiliser ds notre projet astro :
> 
> ```shell
> # https://www.npmjs.com/package/react-twitch-embed
> # https://github.com/moonstar-x/react-twitch-embed
> pnpm add --save react-twitch-embed
> ```
> 
> * Step 3, Ajouter un `XTwitchPlayer.tsx` avec le code suivant :
> 
> ```tsx
> import React from 'preact/compat';
> import { TwitchClip } from 'react-twitch-embed'; // <TwitchClip clip="AdventurousBusyWormTwitchRaid-7vDEE8L5ur9j9dzi" autoplay muted />
> 
> const XTwitchPlayer = () => {
>   return (
>     <TwitchClip clip="AdventurousBusyWormTwitchRaid-7vDEE8L5ur9j9dzi" autoplay muted />
>   );
> };
> 
> export default XTwitchPlayer;
> ```
> 
> * step 4, dans un `*.astro`, je vais utiliser `<TwitchClip clip="AdventurousBusyWormTwitchRaid-7vDEE8L5ur9j9dzi" autoplay muted />`
> 
> ce composant a déjà une qualité : il est vraiment responsive, j'ai testé. Sa performance, nous verrons.
> 
> #### Quelques références de discussions sur le sujet "Le Twitch embed démoli la perf de mon site web"
> * https://discuss.dev.twitch.tv/t/how-to-mitigate-huge-performance-impact-of-a-twitch-embed/28182/2   là il parle d'un évènement "`DOMContentLoaded`"

J'ai trouvé un pattern applicable à tout "embedded  player" , qui permet de résoudre le problème de performances, cf. https://github.com/3forges/juste-un-curieux/pull/20#issuecomment-1703995194

**Comment by Jean-Baptiste-Lasselle** [comment]
* J'ai résolu le pb de score performance ds l'audit lihghthouse, cf. [cette explication](https://github.com/3forges/juste-un-curieux/pull/20#issuecomment-1703998688)
* la solution que j'ai trouvée implique qu'au moment de commencer un nouveau live, une nouvelle release soit faite atomatiquement.
* pour automatiser ce déploiement, et justifier le fait que l'onne peutpas ping l'api twtch depuis notre frontend : 
  * https://github.com/barrycarlyon/twitch_discord_barrycarlyon_co_uk : outil à modifier, mais je garde la notification discord, c'est ce serveur qui va exécuter la git flow release, en requiérant un login with github
  * cette entrée du discourse twitch confirme qu'il n'est pas possible de taper la REST api twitch sans authentification, impossible depuis le front

**Comment by Jean-Baptiste-Lasselle** [comment]
Très intéressant, sur lighthouse : 
* Je viens de faire un commit ajoutant essentiellement des animations,  de manière exagérée, avec le package `tailwindcss-animated` (un plugin tailwindcss ) https://justincurieux-feature-crt-crk6iqwz9-jean-baptiste-lasselle.vercel.app/#_

```bash
$ git rev-parse HEAD
e4fc42c3fb741c0593bac2eadd1ecbd535b9df7b
```

* Et cela a tué mon score de performance, le descendant à `75%` au lieu de `97%`  
* j'ai examiné l'ensemble des métrique, et non seulement la page a un LCP égale à 1.1secondes, mais ne plus une seule métrique a été affectée: le Cumulative Layout Shift. Cette métrique mesure une sorte "d'entropie de mouvement inattendus" dans la page. https://web.dev/cls/

![image](https://github.com/3forges/juste-un-curieux/assets/35227860/32431b92-f5cf-4564-b573-d5e2c8391a7d)


### Après avoir supprimé toutes les animations que j'avais ajoutées

J'ai constaté que la performance était toujours exactement au même niveau (75%) .

Hormis les animations tailwind css, je n'vais apporté qu'un seul changement : j'avais utilisé une "cascade de composants preact", (un compoant , qui importe un composant , qui importe un composant - 3 niveaux), le tout hydraté avec `client:only="preact"`. 

J'ai retiré ces changements impliquant _"un Tsx, qui importe un TSX, qi importe un TSX"_ : et là ça y est, j'ai récupéré toute ma performance.

Moralité: l'hydratation, oui, ça peut coûter cher.

https://justincurieux-feature-crt-6km3pfj4r-jean-baptiste-lasselle.vercel.app/

```bash
$ git rev-parse HEAD
f8243add2ac4f3188fa18089605796b64f1a2d57
```


### Puis j'ai rajouté un peu d'animation et le package `tailwindcss-animated`

et là j'ai à nouveau obtenu un super score :) : 

![image](https://github.com/3forges/juste-un-curieux/assets/35227860/dd4e49c0-3a7a-430f-9e32-fc80ad25ac05)


Donc les animatiosn css avec tailwind ne tuent pas du tout mon score lighthouse, ou ma performance. cf. https://justincurieux-feature-crt-9lvgs33kh-jean-baptiste-lasselle.vercel.app/ et : 

```bash
$ git rev-parse HEAD
e6afdba01c78a45fd687ab6f9ab5458833803c75
```

### Et comment vais-je implémenter le "drawer" ? 

De la même manière que le hamburger menu dans `~/components/header.astro`

**Comment by Jean-Baptiste-Lasselle** [comment]
Tiens pour le "On Air" : 
* essayer ça : https://codepen.io/nodws/pen/WNjXbr
* sinon la sémantique ce serait que le ON AIR soit gris foncé quand aucun live n'est en cours, et rouge néon bien flashy, avec la bordure, quand un live est en cours.
* il faudrait la couleur néon et la même sémantiqeue, pour le nbouton plau, et le bouton ON AIR dnas le menu: on fait la proposition comme cela.

Une fois cela terminé:
* on passe à l'optimisation des images, 
* puis les liens réseaux sociaux configurables par CRUD fichiers Markdown
* Justin démarre un live avec l'application locale qui a le contrôle d'OBS : cette appli va permettre de sélectionner/configurer un overlay (qui est fait avec un theme css tailwind), 
* pas besoin d'envoyer une requête  au serveur qui attrape le webhook twitch, pour enchaîner avec le reste

Les deux applis web, cela va faire juste, en terme de temps pour la prochaine livraison, donc on fera le scénario suivant : 
* on fait une release github pour changer l'état du live : il me faut une commande `pnpm run toggle:onair`, qui va modifier le code source (ou plutôt la configuration), pour que le ONAIR=true et donc changer le css appliqué au deux boutons, de ce côté c'est une configuration `config.ts` qu'il nous faudrait typiquement, avec une valeur `process.env.ONAIR` , dont la valeur par défaut est `false`, `export ONAIR=true && pnpm run build` serace qui sera executé par `pnpm run toggle:onair`.Reste ensuite simplement à faire la git release et le déploiement s'opère automatiquement. C'est l'appli web contrôlant OBS, qui va exécuter automatiquement cela, et le live ne commence que lorsque le déploiement est terminé. Avant le déploiement il est obligatoire de choisir un overlay, ce qui sélectionne un thème Tailwind CSS, que j'appliquerai aussi au déploiement ? (thème par défaut idem `proces.env.DEFAULT_TW_THEME`. 
* Enfin, l'appli qui attrape le webhook de twitch, ne sert qu'à envoyer des notifications twitch : 
  * aux membres d'une équipe particulière, les community hackers
  * à tous les membres du salon discord en tant qu'auditeurs / téléspectateurs
  * tous reçoivent automatiquement les infos dont ils ont besoin : lien pour voir la vidéo en live et chatter, liens pour partager sur tous les réseaux sociaux
  * ce serveur aura aussi pour rôle de faire le robot Twitch : toutes les fonctionnalités auxquelles on pourra penser, comme pouvoir accorder le droits d'exécuter une commande de modérateur à user ds le chat
  * ce serveur pourra aussi servir de robot discord: robots qi pourra avoiir des commandes, il y a aussi d speech 2text ds l'api discord 
* on lance le live avec OBS et l'Overlay choisit par Justin 
* et derrière on voit que le live est dispo sur le site




### Petit ajout design "ON AIR"

J'ai ajouté une animation `tailwindcss` de type `animate-typing`, et impecc atoujors la perf au top: 

* https://justincurieux-feature-crt-dmeejf0mm-jean-baptiste-lasselle.vercel.app/ 

```bash
$ git rev-parse HEAD
1f1e3077c7f1f7bedc15e6ef7d6ffb96ff1f45d1
```

![image](https://github.com/3forges/juste-un-curieux/assets/35227860/91b42289-9538-439c-a4be-877464e3d824)

**Comment by Jean-Baptiste-Lasselle** [comment]
* Sources d'inspiration pour un "Live status button/indicator" : 

https://flowbite.com/docs/components/indicators/#badge-indicator


L'indicateur pourra alors aussi servir de bouton pour le share ?

**Comment by Jean-Baptiste-Lasselle** [comment]
On en reste là où le composant en est, à savoir `src/components/TwitchPlayerX.tsx`, le bouton play sera amélioré plus tard avec une nouvelle issue
