### ISSUE TITLE
aligenment horizontal des vidéos youtubes

### ISSUE THREAD

**Issue by Jean-Baptiste-Lasselle** [3forges/juste-un-curieux#43]
![image](https://github.com/3forges/juste-un-curieux/assets/35227860/047281ae-eae2-42b9-a6b5-802c1b438f4c)

donc ça doit rester aligner qlq soit la longueur du texte

bref, c'est de l'amélioration HTML tailwind css

**Comment by BorisTherin** [comment]
fixed here https://github.com/3forges/juste-un-curieux/commit/cab11f29ce3ba07274faa432bf3185938e7f07a9

![image](https://github.com/3forges/juste-un-curieux/assets/89749441/5e3fe446-1219-4979-978b-5278cbff45a4)

**Comment by Jean-Baptiste-Lasselle** [comment]
revue et résolue! :) https://github.com/3forges/juste-un-curieux/pull/34#issuecomment-1902099471

https://justincurieux-boris-dropup-refined-aae85i13z.vercel.app/
