### ISSUE TITLE
LogoSVG.tsx

### ISSUE THREAD

**Issue by BorisTherin** [3forges/juste-un-curieux#45]
ce composant est responsable du malaise responsive qui laisse une marge a droite inoccupée

**Comment by Jean-Baptiste-Lasselle** [comment]
@BorisTherin ok du coup voilà ta première issue à traiter sur ta nouvelle branche `boris/new/branch` : et tu peux ouvrir une PR pour cette tâche

**Comment by Jean-Baptiste-Lasselle** [comment]
cette tâche consistait à résoudre le problème de responsivité du menu header, @BorisTherin a résolu cela, dans la PR https://github.com/3forges/juste-un-curieux/pull/51
