### ISSUE TITLE
left todos

### ISSUE THREAD

**Issue by Jean-Baptiste-Lasselle** [3forges/juste-un-curieux#46]
* [x] (@BorisTherin ) gallerie yotube, virer tout les encadrés noirs
* [x] (@BorisTherin ) les pb de responsivité les derniers à régler : cf. https://github.com/3forges/juste-un-curieux/pull/34#issuecomment-1905656811
* [x] (@BorisTherin ) le bouton share à ré-implémenter https://sdorra.dev/posts/2023-01-05-share-button
* [x] (@BorisTherin ) les liens vers les réseaux sociaux dans le footer
* [x] (@Jean-Baptiste-Lasselle ) et le traitement des images : pour ça, faire un upgrade à astro 4
* [x] (  @BorisTherin ) : régler les petits pb accessibilité en desktop:

![image](https://github.com/3forges/juste-un-curieux/assets/35227860/8a01cc6e-dec6-4da3-885e-30c6640f3491)

**Comment by Jean-Baptiste-Lasselle** [comment]
pour le plaisir ^^ 

![image](https://github.com/3forges/juste-un-curieux/assets/35227860/fd0b7432-19d0-45c3-8c7c-447cedd92061)

**Comment by BorisTherin** [comment]
Assecibiliy 100! commit :
[https://github.com/3forges/juste-un-curieux/commit/18f0d09d5719fe8663a31db4ca20ddb43c721c58](https://github.com/3forges/juste-un-curieux/commit/18f0d09d5719fe8663a31db4ca20ddb43c721c58)

[https://pagespeed.web.dev/analysis/https-justincurieux-boris-dropup-refined-61nlo3z78-vercel-app/efqn1hfotm?form_factor=desktop](https://pagespeed.web.dev/analysis/https-justincurieux-boris-dropup-refined-61nlo3z78-vercel-app/efqn1hfotm?form_factor=desktop)
![image](https://github.com/3forges/juste-un-curieux/assets/89749441/3f9ca91d-d898-4eeb-89ec-9bdd3824ae31)

**Comment by Jean-Baptiste-Lasselle** [comment]
toutes ces tâches ont été terminées avec le merge de la PR https://github.com/3forges/juste-un-curieux/pull/58
