### ISSUE TITLE
Debug@4.3.4 error

### ISSUE THREAD

**Issue by BorisTherin** [3forges/juste-un-curieux#48]
une nouvelle erreur a proc dans la console browser:

![image](https://github.com/3forges/juste-un-curieux/assets/89749441/3ce30c36-0ddb-4cd2-890d-e43662fd49ac)

```
custom.mjs?v=2e9853eb:1 Uncaught (in promise) SyntaxError: The requested module '/node_modules/.pnpm/debug@4.3.4/node_modules/debug/src/browser.js?v=2e9853eb' does not provide an export named 'default' (at custom.mjs?v=2e9853eb:1:8)
```

**Comment by Jean-Baptiste-Lasselle** [comment]
L'issue n'existe plus, elle était probablement due à des spécificités locales au poste de dev
