### ISSUE TITLE
fiabilisation du composant de partage sur les reseaux sociaux

### ISSUE THREAD

**Issue by BorisTherin** [3forges/juste-un-curieux#49]
suite à la migration il nous reprendre ce composant, et on en profitera pour changer de strategie concernant les childrens & rendre ca plus fiable et perien.

PR: https://github.com/3forges/juste-un-curieux/pull/51

**Comment by BorisTherin** [comment]
ok, du coup je me rend compte que nos share-options sont à la rue.
c.a.d. par exemple, on ne peut partager sur twitch, et sur youtube il faudrais limiter à l'onglet communauté.

reste facebook& discord, eventuellement en ajouter d'autres comme twitter.

(cf https://www.leptidigital.fr/reseaux-sociaux/liste-reseaux-sociaux-14846/)

**Comment by Jean-Baptiste-Lasselle** [comment]
donc on a utilisé `react-share`, et le comportement quand on scroll, le btn share se referme automatiquement, et ça marche

**Comment by Jean-Baptiste-Lasselle** [comment]
https://github.com/3forges/juste-un-curieux/pull/51
