### ISSUE TITLE
videoGallery : should switch dark/light theme with the theme-switcher

### ISSUE THREAD

**Issue by BorisTherin** [3forges/juste-un-curieux#52]
notre composant pagination n'est pas compatible avec la navigation Light/Dark de notre theme-switcher.

nous changerons son comportement pour enlever son background-white forcé & afin que sa couleur soit definit par notre theme switcher

**Comment by Jean-Baptiste-Lasselle** [comment]
résolu par @BorisTherin  avec https://github.com/3forges/juste-un-curieux/pull/58
